# Generated by Django 5.0.1 on 2025-08-07 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del proyecto', max_length=200, verbose_name='Nombre del Proyecto')),
                ('client', models.CharField(help_text='Nombre del cliente o empresa', max_length=150, verbose_name='Cliente')),
                ('location', models.CharField(help_text='Dirección o zona del proyecto', max_length=200, verbose_name='Ubicación')),
                ('project_type', models.CharField(choices=[('residential', 'Residencial'), ('commercial', 'Comercial'), ('institutional', 'Institucional'), ('industrial', 'Industrial')], default='residential', max_length=20, verbose_name='Tipo de Proyecto')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del proyecto', verbose_name='Descripción')),
                ('start_date', models.DateField(help_text='Fecha de inicio del proyecto', verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Fecha planificada de finalización', null=True, verbose_name='Fecha de Finalización')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Finalización')),
                ('current_phase', models.CharField(choices=[('design', 'Diseño'), ('purchase', 'Compra'), ('installation', 'Instalación'), ('completed', 'Completado')], default='design', max_length=20, verbose_name='Fase Actual')),
                ('status', models.CharField(choices=[('planning', 'PLANIFICACIÓN'), ('in_progress', 'EN PROGRESO'), ('on_hold', 'EN PAUSA'), ('completed', 'TERMINADO'), ('budget', 'PRESUPUESTO')], default='planning', max_length=20, verbose_name='Estado del Proyecto')),
                ('drive_folder_url', models.URLField(blank=True, help_text='Link a la carpeta de Google Drive del proyecto', validators=[django.core.validators.URLValidator()], verbose_name='URL Carpeta Google Drive')),
                ('initial_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto inicial estimado del proyecto', max_digits=12, null=True, verbose_name='Presupuesto Inicial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_selected', models.BooleanField(default=False, help_text='Indica si este proyecto está actualmente seleccionado en la app', verbose_name='Proyecto Seleccionado')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
