# Generated by Django 5.0.1 on 2025-08-07 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Categoría')),
                ('category_type', models.CharField(choices=[('construction', 'Construcción'), ('lighting', 'Iluminación'), ('electrical', 'Eléctrico'), ('plumbing', 'Plomería'), ('finishes', 'Acabados'), ('others', 'Otros')], max_length=20, verbose_name='Tipo de Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Categoría de Material',
                'verbose_name_plural': 'Categorías de Materiales',
                'db_table': 'material_categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Material')),
                ('code', models.CharField(help_text='Código único para identificar el material', max_length=50, unique=True, verbose_name='Código del Material')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramos'), ('saco', 'Sacos'), ('m2', 'Metros Cuadrados'), ('m3', 'Metros Cúbicos'), ('ml', 'Metros Lineales'), ('litros', 'Litros'), ('galones', 'Galones'), ('unidad', 'Unidades'), ('metros', 'Metros'), ('rollo', 'Rollos'), ('pieza', 'Piezas'), ('par', 'Pares'), ('kit', 'Kits')], max_length=20, verbose_name='Unidad de Medida')),
                ('yield_per_unit', models.DecimalField(blank=True, decimal_places=4, help_text='Cuánto rinde cada unidad (ej: m2 por saco de cemento)', max_digits=10, null=True, verbose_name='Rendimiento por Unidad')),
                ('waste_factor', models.DecimalField(decimal_places=4, default=0.05, help_text='Porcentaje de desperdicio típico (0.05 = 5%)', max_digits=5, verbose_name='Factor de Desperdicio')),
                ('reference_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio promedio de referencia', max_digits=10, null=True, verbose_name='Precio de Referencia')),
                ('last_price_update', models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización de Precio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coverage_per_liter', models.DecimalField(blank=True, decimal_places=2, help_text='Para pintura: metros cuadrados que cubre un litro', max_digits=8, null=True, verbose_name='Cobertura por Litro (m²)')),
                ('density', models.DecimalField(blank=True, decimal_places=3, help_text='Densidad del material (kg/m³)', max_digits=8, null=True, verbose_name='Densidad')),
                ('power_per_meter', models.DecimalField(blank=True, decimal_places=2, help_text='Para cintas LED: watts por metro', max_digits=6, null=True, verbose_name='Potencia por Metro (W/m)')),
                ('wire_gauge', models.CharField(blank=True, help_text='Calibre del cable eléctrico', max_length=20, verbose_name='Calibre')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.materialcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'materials',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification_type', models.CharField(help_text='Ej: color, acabado, dimensión, voltaje', max_length=50, verbose_name='Tipo de Especificación')),
                ('value', models.CharField(max_length=100, verbose_name='Valor')),
                ('is_default', models.BooleanField(default=False, verbose_name='Por Defecto')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='materials.material')),
            ],
            options={
                'verbose_name': 'Especificación de Material',
                'verbose_name_plural': 'Especificaciones de Materiales',
                'db_table': 'material_specifications',
                'unique_together': {('material', 'specification_type', 'value')},
            },
        ),
    ]
