# Generated by Django 5.0.1 on 2025-08-07 04:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('projects', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descripción detallada del material o servicio', max_length=300, verbose_name='Descripción del Item')),
                ('category', models.CharField(choices=[('construction', 'Construcción'), ('lighting', 'Iluminación'), ('electrical', 'Eléctrico'), ('labor', 'Mano de Obra'), ('others', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('spaces', models.CharField(blank=True, help_text='Espacios o áreas donde se aplicará', max_length=200, verbose_name='Espacios')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad')),
                ('unit', models.CharField(help_text='Unidad de medida', max_length=20, verbose_name='Unidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Se calcula automáticamente: cantidad × precio unitario', max_digits=12, verbose_name='Precio Total')),
                ('notes', models.TextField(blank=True, help_text='Observaciones adicionales', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_from_calculation', models.BooleanField(default=False, help_text='Indica si este item fue creado automáticamente desde una calculadora', verbose_name='Creado desde Calculadora')),
                ('material', models.ForeignKey(blank=True, help_text='Material asociado (opcional si es servicio)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.material', verbose_name='Material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='projects.project', verbose_name='Proyecto')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='Proveedor Seleccionado')),
            ],
            options={
                'verbose_name': 'Item de Presupuesto',
                'verbose_name_plural': 'Items de Presupuesto',
                'db_table': 'budget_items',
                'ordering': ['category', 'description'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Presupuestado')),
                ('budget_construction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Presupuesto Construcción')),
                ('budget_lighting', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Presupuesto Iluminación')),
                ('budget_others', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Presupuesto Otros')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Gastado')),
                ('expenses_construction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gastos Construcción')),
                ('expenses_lighting', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gastos Iluminación')),
                ('expenses_others', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Gastos Otros')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Presupuesto - Gastos (positivo = ahorro, negativo = sobrecosto)', max_digits=15, verbose_name='Balance')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summary', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Resumen Financiero',
                'verbose_name_plural': 'Resúmenes Financieros',
                'db_table': 'project_financial_summaries',
            },
        ),
        migrations.CreateModel(
            name='RealExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Descripción del Gasto')),
                ('category', models.CharField(choices=[('construction', 'Construcción'), ('lighting', 'Iluminación'), ('electrical', 'Eléctrico'), ('labor', 'Mano de Obra'), ('others', 'Otros')], max_length=20, verbose_name='Categoría')),
                ('spaces', models.CharField(blank=True, max_length=200, verbose_name='Espacios')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento (Monto Fijo)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Precio final después de descuentos', max_digits=12, verbose_name='Precio Total')),
                ('purchase_date', models.DateField(verbose_name='Fecha de Compra')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Número de Factura')),
                ('payment_method', models.CharField(blank=True, help_text='Efectivo, tarjeta, transferencia, etc.', max_length=50, verbose_name='Método de Pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_item', models.ForeignKey(blank=True, help_text='Item del presupuesto del cual proviene este gasto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_expenses', to='budgets.budgetitem', verbose_name='Item de Presupuesto Relacionado')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.material', verbose_name='Material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_expenses', to='projects.project', verbose_name='Proyecto')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Gasto Real',
                'verbose_name_plural': 'Gastos Reales',
                'db_table': 'real_expenses',
                'ordering': ['-purchase_date', 'category'],
            },
        ),
    ]
